### ISSUE TITLE
Agony resistance in the "hero panel"

### ISSUE THREAD

**Issue by Janitsu** [discretize/discretize-gear-optimizer#224]
In the hero panel section of the gear optimiser (after running the calculations), the amount of agony resistance is shown as 0xxx where "xxx" stands for the amount that was input in the original calcs. Below are a few images to clarify.

![image](https://user-images.githubusercontent.com/8763688/132263473-855bf702-7c66-4c9f-9fc9-e6911a63107b.png)
![image](https://user-images.githubusercontent.com/8763688/132263480-74292bae-a675-4950-bf0c-712cc0edcf7f.png)

**Comment by marcustyphoon** [comment]
Fixed! There are a few other textbox inputs that still need this treatment, though.
