### ISSUE TITLE
Contact information for translators

### ISSUE THREAD

**Issue by Janitsu** [discretize/discretize-gear-optimizer#470]
![image](https://user-images.githubusercontent.com/8763688/168454541-0fca30f5-4704-458d-8e33-199b61c9a553.png)

This notice could have contact information on it (especially if preferred method of contact is different than the ones mentioned in the other bubble). At the moment, there are two bubbles, but in the future there might only be one and then it would be missing contact information.

**Comment by marcustyphoon** [comment]
Agreed! I have removed this banner, however, as right now I don't think we have the resources to do more translations anyway unless someone is willing to put in most of the work themself, in which case I assume they will reach out of their own accord.
