### ISSUE TITLE
Error with forced slots & weapon types

### ISSUE THREAD

**Issue by Zerthox** [discretize/discretize-gear-optimizer#477]
An edge case error related to forced slots & weapon types. The error occurs whenever the user has selected a forced stat for Weapon 2 but switched the weapon type to Two-handed.

Steps to reproduce:
1. Select Dual wielded as weapon type
2. Force any stat on the Weapon 2 slot
3. Switch to Two-handed as weapon type
4. Press calculate

**Comment by marcustyphoon** [comment]
Fixed in 9b58a93!
